const Holidays = [
  {
    date: "21-02-2022",
    monthName: "February",
    day: 21,
    description: "International Mother Language Day",
  },
  {
    date: "17-03-2022",
    monthName: "March",
    day: 17,
    description: "Birthday of Bangabandhu",
  },
  {
    date: "18-03-2022",
    monthName: "March",
    day: 18,
    description: "Shab e-Barat",
  },
  {
    date: "26-03-2022",
    monthName: "March",
    day: 26,
    description: "Independence Day of Bangladesh",
  },
  {
    date: "14-04-2022",
    monthName: "April",
    day: 14,
    description: "Bengali New Year",
  },
  {
    date: "29-04-2022",
    monthName: "April",
    day: 29,
    description: "Laylat ul-Qadr",
  },
  {
    date: "29-04-2022",
    monthName: "April",
    day: 29,
    description: "Jumatul Bidah",
  },
  {
    date: "01-05-2022",
    monthName: "May",
    day: 1,
    description: "May Day",
  },
  {
    date: "02-05-2022",
    monthName: "May",
    day: 2,
    description: "Eid ul-Fitr",
  },
  {
    date: "03-05-2022",
    monthName: "May",
    day: 3,
    description: "Eid ul-Fitr",
  },
  {
    date: "04-05-2022",
    monthName: "May",
    day: 4,
    description: "Eid ul-Fitr",
  },
  {
    date: "16-05-2022",
    monthName: "May",
    day: 16,
    description: "Buddha Purnima",
  },
  {
    date: "09-07-2022",
    monthName: "July",
    day: 9,
    description: "Eid ul-Adha",
  },
  {
    date: "10-07-2022",
    monthName: "July",
    day: 10,
    description: "Eid ul-Adha",
  },
  {
    date: "11-07-2022",
    monthName: "July",
    day: 11,
    description: "Eid ul-Adha",
  },
  {
    date: "09-08-2022",
    monthName: "August",
    day: 9,
    description: "Ashura",
  },
  {
    date: "15-08-2022",
    monthName: "August",
    day: 15,
    description: "National Mourning Day",
  },
  {
    date: "18-08-2022",
    monthName: "August",
    day: 18,
    description: "Shuva Janmashtami",
  },
  {
    date: "05-10-2022",
    monthName: "October",
    day: 5,
    description: "Vijaya Dashami",
  },
  {
    date: "09-10-2022",
    monthName: "October",
    day: 9,
    description: "Eid-e-Milad un-Nabi",
  },
  {
    date: "16-12-2022",
    monthName: "December",
    day: 16,
    description: "Victory Day of Bangladesh",
  },
  {
    date: "25-12-2022",
    monthName: "December",
    day: 25,
    description: "Christmas Day",
  },
];
export default Holidays;
